plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}
tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

group = mod_group_id
version = mod_version

base {
    archivesName = minecraft_version + "-" + mod_id
}


java.toolchain.languageVersion = JavaLanguageVersion.of(25)
java.withSourcesJar()

neoForge {
    version = project.neo_version

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'terminal.jline', 'true'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    flatDir {
        dir 'libs'
    }
    maven {
        url "https://cursemaven.com"
    }
    maven {
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        name = "IPN-Releases"
        mavenContent {
            releasesOnly()
        }
        content {
            includeGroup("org.anti_ad.mc")
            includeGroup("ca.solo-studios")
        }
        url = uri("https://maven.ipn-mod.org/releases")
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven { url = "https://maven.ithundxr.dev/snapshots" }
    maven { url "https://maven.shedaniel.me/" }
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.architectury.dev/" }
    maven { url = "https://maven.latvian.dev/releases" }
    maven { url 'https://jitpack.io' }
    maven {
        url = "https://api.modrinth.com/maven"
        name = "Modrinth"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url = "https://maven.ryanhcode.dev/releases"
        name = "RyanHCode Maven"
        content {
            includeGroup "dev.ryanhcode.sable"
            includeGroup "dev.ryanhcode.sable-companion"
        }
    }
}

dependencies {
    compileOnly "libs:touhoulittlemaid:2.0.0-neoforge+mc26.1.2-all"
    runtimeOnly "libs:touhoulittlemaid:2.0.0-neoforge+mc26.1.2-all"

//    runtimeOnly "curse.maven:accelerated-rendering-1314021:6839175"

//    compileOnly "org.anti_ad.mc:InventoryProfilesNext-neoforge-1.21:2.1.10"
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    compileOnly "curse.maven:applied-energistics-2-223794:8129795"
//    compileOnly "curse.maven:mouse-tweaks-60089:5637846"
    compileOnly "curse.maven:mouse-tweaks-60089:7840778"
//    compileOnly "curse.maven:just-enough-characters-250702:6681787"
//    compileOnly "dev.emi:emi-neoforge:${emi_version}:api"
//    compileOnly "dev.emi:emi-neoforge:${emi_version}"
//    compileOnly "curse.maven:create-328085:7149903"
//    compileOnly "com.tterrag.registrate:Registrate:MC1.21-1.3.0+67"
//    compileOnly "net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:1.0.60"
//    compileOnly "curse.maven:refined-storage-243076:6798977"
//    compileOnly "libs:tacz-neoforge-1.21.1:1.1.6-hotfix-r5"
    compileOnly("maven.modrinth:cloth-config:26.1.154+neoforge")
//    compileOnly "mekanism:Mekanism:${mekanism_version}"
//    compileOnly "dev.latvian.mods:kubejs-neoforge:${kubejs_version}"
//    compileOnly "dev.latvian.mods:rhino-neoforge:${rhino_version}"
//    compileOnly "dev.architectury:architectury-neoforge:${architectury_version}"
//    compileOnly "curse.maven:ars-nouveau-401955:6770346"
//    compileOnly "curse.maven:geckolib-388172:6659026"
    compileOnly "maven.modrinth:jade:26.1.1+neoforge"
    compileOnly "maven.modrinth:inventory-profiles-next:neoforge-26.1-2.3.2"
//    compileOnly "curse.maven:jade-324717:6738687"
    compileOnly "curse.maven:sophisticated-storage-619320:8185754"

//    runtimeOnly "libs:tacz-neoforge-1.21.1:1.1.6-hotfix-r5"

    runtimeOnly "curse.maven:applied-energistics-2-223794:8129795"
    runtimeOnly "curse.maven:guideme-1173950:8129704"
//    runtimeOnly "com.tterrag.registrate:Registrate:MC1.21-1.3.0+67"
//    runtimeOnly "curse.maven:patchouli-306770:6164617"
//    runtimeOnly "curse.maven:sophisticated-storage-619320:6759132"
//    runtimeOnly "curse.maven:sophisticated-core-618298:6760141"
//    runtimeOnly "curse.maven:mouse-tweaks-60089:5637846"
//    runtimeOnly "curse.maven:create-328085:7149903"
    runtimeOnly("maven.modrinth:cloth-config:26.1.154+neoforge")
    runtimeOnly "maven.modrinth:curios:15.0.0-beta.2+26.1.2-neoforge"
//    runtimeOnly "curse.maven:refined-storage-243076:6798977"
//    runtimeOnly "mekanism:Mekanism:${mekanism_version}"
//    runtimeOnly "mekanism:Mekanism:${mekanism_version}:additions"
//    runtimeOnly "mekanism:Mekanism:${mekanism_version}:generators"
//    runtimeOnly "mekanism:Mekanism:${mekanism_version}:tools"
//    runtimeOnly "curse.maven:ars-nouveau-401955:6770346"
    runtimeOnly "maven.modrinth:jade:26.1.1+neoforge"
//    runtimeOnly "org.anti_ad.mc:InventoryProfilesNext-neoforge-1.21:2.1.10"
//    runtimeOnly "org.anti_ad.mc:libIPN-neoforge-1.21:6.5.1"
//    runtimeOnly "curse.maven:kotlin-for-neoforge-351264:6706911"
//    runtimeOnly "curse.maven:geckolib-388172:6659026"

}


var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

publishMods {
    type = BETA
    file = jar.archiveFile
    modLoaders.add("neoforge")
    changelog = file("changelog").text

    curseforge {
        projectId = "1210244"
        accessToken = CURSEFORGE_TOKEN
        minecraftVersions.add("1.21.1")
        optional("applied-energistics-2","ars-nouveau","botania","cloth-config","create","emi","jei","kubejs","mekanism","patchouli","refined-storage")
        requires("touhou-little-maid")
    }
    modrinth {
        projectId = "5sIJPqAj"
        accessToken = MODRINTH_TOKEN
        minecraftVersions.add("1.21.1")
        optional("kubejs","emi","jei","refined-storage","patchouli","cloth-config","ars-nouveau","ae2","create","mekanism")
        requires("touhou-little-maid")
    }
}
tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:-removal']
    options.encoding = 'UTF-8'
    options.warnings = false
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}