package studio.fantasyit.maid_storage_manager.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.TagsProvider;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagEntry;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import org.jetbrains.annotations.NotNull;
import studio.fantasyit.maid_storage_manager.MaidStorageManager;

import java.util.concurrent.CompletableFuture;

public class TagGenBlock extends TagsProvider<Block> {

    protected TagGenBlock(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(output, Registries.BLOCK, lookupProvider, MaidStorageManager.MODID);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "working_block/furnace")))
                .addElement(BuiltInRegistries.BLOCK.getKey(Blocks.FURNACE));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "working_block/stone_cutter")))
                .addElement(BuiltInRegistries.BLOCK.getKey(Blocks.STONECUTTER));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "working_block/brewing_stand")))
                .addElement(BuiltInRegistries.BLOCK.getKey(Blocks.BREWING_STAND));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "working_block/crafting_table")))
                .addElement(BuiltInRegistries.BLOCK.getKey(Blocks.CRAFTING_TABLE));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "working_block/smithing_table")))
                .addElement(BuiltInRegistries.BLOCK.getKey(Blocks.SMITHING_TABLE));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "default_storage_blocks")))
                .add(TagEntry.tag(Identifier.fromNamespaceAndPath("c", "chests")))
                .add(TagEntry.tag(Identifier.fromNamespaceAndPath("c", "barrels")))
                .addElement(BuiltInRegistries.BLOCK.getKey(Blocks.SHULKER_BOX))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ae2", "cable_bus"))
                .add(TagEntry.optionalTag(Identifier.fromNamespaceAndPath("refinedstorage", "grid")))
                .add(TagEntry.optionalTag(Identifier.fromNamespaceAndPath("refinedstorage", "crafting_grid")))
                .addOptionalElement(Identifier.fromNamespaceAndPath("mekanism", "qio_dashboard"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "barrel"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "copper_barrel"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "iron_barrel"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "gold_barrel"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "diamond_barrel"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "netherite_barrel"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_copper_barrel_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_copper_barrel_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_3"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_copper_barrel_3"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_3"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_3"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_3"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_3"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_barrel_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_copper_barrel_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_iron_barrel_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_gold_barrel_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_diamond_barrel_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "limited_netherite_barrel_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "netherite_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "shulker_box"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "copper_shulker_box"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "iron_shulker_box"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "gold_shulker_box"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "diamond_shulker_box"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "netherite_shulker_box"))
                .add(TagEntry.optionalTag(Identifier.fromNamespaceAndPath("drawers", "storagedrawers")))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ars_nouveau", "repository"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "item_vault"))
                .add(TagEntry.optionalTag(Identifier.fromNamespaceAndPath("create", "toolboxes")))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "stock_ticker"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedbackpacks", "iron_backpack"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedbackpacks", "gold_backpack"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedbackpacks", "diamond_backpack"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedbackpacks", "netherite_backpack"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedbackpacks", "backpack"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "oak_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "spruce_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "birch_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "jungle_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "acacia_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "dark_oak_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "crimson_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "warped_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "mangrove_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "cherry_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "framed_1"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "oak_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "spruce_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "birch_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "jungle_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "acacia_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "dark_oak_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "crimson_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "warped_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "mangrove_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "cherry_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "framed_4"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "oak_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "spruce_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "birch_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "jungle_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "acacia_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "dark_oak_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "crimson_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "warped_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "mangrove_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "cherry_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("functionalstorage", "framed_2"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "oak_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "oak_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "oak_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "oak_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_oak_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "oak_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "oak_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "birch_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "birch_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "birch_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "birch_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_birch_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "birch_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "birch_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "spruce_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "spruce_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "spruce_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "spruce_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_spruce_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "spruce_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "spruce_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "jungle_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "jungle_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "jungle_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "jungle_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_jungle_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "jungle_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "jungle_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "acacia_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "acacia_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "acacia_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "acacia_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_acacia_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "acacia_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "acacia_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "dark_oak_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "dark_oak_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "dark_oak_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "dark_oak_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_dark_oak_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "dark_oak_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "dark_oak_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "mangrove_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "mangrove_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "mangrove_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "mangrove_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_mangrove_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "mangrove_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "mangrove_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "cherry_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "cherry_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "cherry_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "cherry_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_cherry_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "cherry_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "cherry_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "pale_oak_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "pale_oak_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "pale_oak_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "pale_oak_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_pale_oak_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "pale_oak_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "pale_oak_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "bamboo_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "bamboo_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "bamboo_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "bamboo_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_bamboo_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "bamboo_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "bamboo_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "crimson_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "crimson_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "crimson_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "crimson_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_crimson_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "crimson_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "crimson_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "warped_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "warped_drawer_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "warped_drawer_with_books"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "warped_bookshelf_with_door"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "glass_warped_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "warped_cabinet_with_glass_doors"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("storagedelight", "warped_single_door_cabinet"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("netherchested", "nether_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "crystal_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "obsidian_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_crystal_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_obsidian_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_white"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_orange"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_magenta"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_light_blue"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_yellow"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_lime"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_pink"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_gray"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_light_gray"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_cyan"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_purple"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_blue"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_brown"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_green"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_red"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "backpack_black"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "ender_drawer"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_white"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_orange"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_magenta"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_light_blue"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_yellow"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_lime"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_pink"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_gray"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_light_gray"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_cyan"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_purple"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_blue"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_brown"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_green"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_red"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("l2backpack", "dimensional_storage_black"))
                .add(TagEntry.optionalTag(Identifier.fromNamespaceAndPath("ironchests", "chests.json")));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "mb_chests")))
                .add(TagEntry.tag(Identifier.fromNamespaceAndPath("c", "chests")))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("sophisticatedstorage", "netherite_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "item_vault"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("netherchested", "nether_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "crystal_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "obsidian_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_crystal_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_obsidian_chest"))
                .add(TagEntry.optionalTag(Identifier.fromNamespaceAndPath("ironchests", "chests.json")));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "sortable_chests")))
                .add(TagEntry.tag(Identifier.fromNamespaceAndPath("c", "chests")))
                .addOptionalElement(Identifier.fromNamespaceAndPath("netherchested", "nether_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "crystal_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "obsidian_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_iron_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_gold_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_diamond_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_copper_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_crystal_chest"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("ironchest", "trapped_obsidian_chest"))
                .add(TagEntry.optionalTag(Identifier.fromNamespaceAndPath("ironchests", "chests.json")));

        getOrCreateRawBuilder(TagKey.create(Registries.BLOCK,
                Identifier.fromNamespaceAndPath(MaidStorageManager.MODID, "create_package_container")))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "belt"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "depot"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "package_frogport"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "weighted_ejector"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "chute"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "basin"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "packager"))
                .addOptionalElement(Identifier.fromNamespaceAndPath("create", "smart_chute"));
    }
}
